name: "LoRa FUOTA Updater"
description: "Update IoT devices with LoRa"
author: "Ignacio Fernandez, Franco Lopez Paviolo"
branding:
  icon: 'refresh-cw'
  color: 'blue'
inputs:
  LORASERVER_IP:
    description: "IP address of the LoRa Server"
    required: true
  LORASERVER_URL:
    description: "URL of the LoRa Server"
    required: true
  LORASERVER_MQTT_PORT:
    description: "MQTT port of the LoRa Server"
    required: false
    default: 1883
  LORASERVER_API_PORT:
    description: "API port of the LoRa Server"
    required: false
    default: 8090
  LORASERVER_API_KEY:
    description: "API key of the LoRa Server"
    required: true
  LORASERVER_TENANT_ID:
    description: "Tenant ID of the LoRa Server"
    required: true
  LORASERVER_DOWNLINK_DR:
    description: "Downlink data rate of the LoRa Server"
    required: false
    default: 5
  LORASERVER_DOWNLINK_FREQ:
    description: "Downlink frequency of the LoRa Server"
    required: false
    default: 869525000
  LORASERVER_APP_ID:
    description: "Application ID of the LoRa Server"
    required: true
  DEVICE_EUI:
    description: "Device EUI"
    required: true
  GITHUB_REPOSITORY:
    description: "Github repository"
    required: true
  GITHUB_TOKEN:
    description: "Github token"
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.LORASERVER_IP }}
    - ${{ inputs.LORASERVER_URL }}
    - ${{ inputs.LORASERVER_MQTT_PORT }}
    - ${{ inputs.LORASERVER_API_PORT }}
    - ${{ inputs.LORASERVER_API_KEY }}
    - ${{ inputs.LORASERVER_TENANT_ID }}
    - ${{ inputs.LORASERVER_DOWNLINK_DR }}
    - ${{ inputs.LORASERVER_DOWNLINK_FREQ }}
    - ${{ inputs.LORASERVER_APP_ID }}
    - ${{ inputs.DEVICE_EUI }}
    - ${{ inputs.GITHUB_REPOSITORY }}
    - ${{ inputs.GITHUB_TOKEN }}
    